# Generated by Django 4.2.6 on 2023-10-30 13:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_drf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='date',
            field=models.DateField(verbose_name=datetime.datetime(2023, 10, 30, 13, 18, 5, 604835, tzinfo=datetime.timezone.utc)),
        ),
    ]
