# Generated by Django 2.2 on 2023-10-20 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_2', '0002_auto_20231020_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_2.NoteUsers')),
            ],
        ),
    ]
