# Generated by Django 2.2 on 2023-10-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_2', '0006_auto_20231020_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteusers',
            name='password',
            field=models.CharField(default='admin', max_length=200),
        ),
    ]
